# Generated by Django 4.2.5 on 2023-10-12 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 12, 22, 49, 21, 793886)),
        ),
    ]
