# Generated by Django 4.2.5 on 2023-10-13 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 13, 22, 31, 23, 937369)),
        ),
    ]
