# Generated by Django 4.2.5 on 2023-10-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_posts_likes_alter_posts_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='created_at',
        ),
    ]
